<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /* Promise
            Promise可以解决回调地狱问题
            Promise是一个构造函数
            Promise接收一个参数,数据类型是函数
                该函数接收两个实参
                    resolve
                        调用该函数会将返回的promise状态变为成功
                    reject
                        调用该函数会将返回的promise状态变为失败
            Promise接收的执行器函数,会被同步调用
            Promise的返回值,是一个promise对象
                一共具有三种状态:
                    pending ->等待状态
                    resolved    ->成功
                    rejected    ->失败
                注意:任何一个promise对象,只要状态发生变化,该变化不可逆


            函数.then
                接收参数数量:2个,而且都必须是函数或者undefined||null
                    第一个回调函数:
                        当被监视的promise状态变为成功的时候,会自动调用
                    第二个回调函数
                        当被监视的promise状态变为失败的时候,会自动调用
                    注意:其实.then不是监视前面的promise对象状态的变化,而是只要前面的promise不是pending就会执行对应回调函数
                    
                返回值:全新的promise对象(p1)
                    状态变化
                        -如何将该promise对象变成成功状态
                            1.如果回调函数的返回值不是一个promise对象,那么p1就会变为成功状态
                                但是return的数据会变成p1的result
                                
                            2.如果回调函数的返回值是一个成功的promise对象,那么p1就会变为成功状态
                                .then并不会把return的promise对象替代掉p1,他只是参考了return的promise对象的状态

                        -如何将该promise对象变成失败状态
                            1.如果回调函数的内部代码没有成功执行结束,那么p1就会变成失败状态
                                
                            2.如果回调函数的返回值是一个失败的promise对象,那么p1就会变为失败状态

                如果.then没有传递对应的回调函数,那么如果需要用到对应函数的时候,.then返回的promise对象会继承上一个promise的状态

            函数.catch
                其实catch就是then的语法糖,它相当于then没传第一个回调函数
                            

        */ 

        // const promise = new Promise((resolve,reject)=>{
        //     // console.log('Promise1')
        //     reject();
        // })
            // console.log('Promise2',promise)

        // let p2 = Promise.resolve();
        // const p1 = promise
        // .then(()=>{
        //     console.log('success1')
        //     // throw new Error();
        //     // return 123;
        //     // return Promise.reject();
        // },()=>{
        //     console.log('fail1')
        // })
        // .then(()=>{
        //     console.log('success2')
        //     // throw new Error();
        //     // return 123;
        //     // return Promise.reject();
        // },()=>{
        //     console.log('fail2')
        // })



        
        // const promise = new Promise((resolve,reject)=>{
        //     setTimeout(()=>{
        //         reject();
        //     },2000)
        // })


        // promise
        // .then(()=>{
        //     console.log('success1')
        // })
        // .then(()=>{
        //     console.log('success2')
        // })
        // .catch(()=>{
        //     console.log('fail3')
        // })


        /*
            async和await
                语法:
                    async必须写在函数名称之前
                    await后面可以书写promise,await会阻塞后续代码的执行
                        await关键字后面跟着promise对象,那么表达式的返回结果相当于是promise对象的result
                        await关键字后面跟着非promise对象的数据,那么表达式的返回结果就是该数据


                        注意:await之后不一定非要写promise对象,其他数据也可以

                async和await其实是promise和.then的语法糖
                async函数的返回值结果是一个全新的promise对象
                    状态变化
                        -如何将该promise对象变成成功状态
                            1.如果回调函数的返回值不是一个promise对象,那么p1就会变为成功状态
                                但是return的数据会变成p1的result
                                
                            2.如果回调函数的返回值是一个成功的promise对象,那么p1就会变为成功状态
                                .then并不会把return的promise对象替代掉p1,他只是参考了return的promise对象的状态

                        -如何将该promise对象变成失败状态
                            1.如果回调函数的内部代码没有成功执行结束,那么p1就会变成失败状态
                                
                            2.如果回调函数的返回值是一个失败的promise对象,那么p1就会变为失败状态

                            3.如果await后面跟的promise对象变成失败状态,那么后续代码将不会继续执行

        
        */
            async function a(){
                const result = await Promise.reject()
                
                console.log(666,result)
                // return Promise.reject();
                return 123;
            }
            // new Promise((resolve)=>{
            //         // setTimeout(()=>{
            //             resolve(666)
            //         // },1000)
            // })
            // .then(()=>{
            //     console.log(result)
            // })

            console.log(1)
            console.log(a());
            
            // new Promise((resolve)=>{
            //         // setTimeout(()=>{
            //             resolve(666)
            //         // },1000)
            // })
            // .then(()=>{
            //     console.log(result)
            // })
            console.log(3)

    </script>
</body>
</html>